continueFlags: ['MISSING_CALIBRATION','MISSING_NORMALIZATION'] #default behaviour will continue in these cases 
defaultUnfocussedWorkspaceUnits: dSpacing
keepUnfocussed: false
pixelMasks: []
useLiteMode: true
artificialNorm:
  smoothingParameter: 0.5
  decreaseParameter: true
  lss: true
  
