[project]
authors = ["Michael Walsh <walshmm@ornl.gov>"]
channels = ["conda-forge", "mantid/label/nightly", "mantid-ornl", "mantid-ornl/label/rc", "neutrons/label/rc"]
name = "SNAPBlue"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snapred = ">=1.1.0rc4"
python = ">=3.8"
versioningit = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
jupyterlab = "*"
ipympl = "*"
pre-commit = "*"
libmamba = "*"
libarchive = "*"
anaconda-client = "*"
boa = "*"
conda-build = "<4"
conda-verify = "*"
python-build = "*"
twine = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
myst-parser = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
pip = "*"

[pypi-dependencies]
bm3d-streak-removal = "*"
pytest-playwright = "*"
